name: Kasus
<<<<<<< HEAD
description: A sample command-line application.
=======
description: A starting point for Dart libraries or applications.
>>>>>>> ec5ece17116e019937a7c1f70ae821f1834b00db
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
